Implement CORS
albburtsev/talaria pull request #4
Opened 2016-03-28 21:00 UTC by masylum

Not sure if you had another idea in mind. I just need to be able to set `withCredentials`.

2016-03-29 05:39 UTC, albburtsev commented
Looks good. Could you update JSDoc about `cors` flag and add JSDoc about `[settings.cors]`?

2016-03-30 07:41 UTC, masylum commented
Done :smile:

2016-03-30 07:42 UTC, masylum commented
I can add tests later on too.

2016-09-30 14:58 UTC, andresgutgon requested changes

2016-09-30 14:58 UTC, andresgutgon commented on src/fetch-please.js
> +            cors: false
Typo you're missing a `,`

2016-10-24 09:01 UTC, JulianWielga commented on src/fetch-please.js
> +            cors: false
this pr looks dead so i fixed this typo in #8

2016-10-24 09:39 UTC, albburtsev commented
Merged in #8.

2016-10-24 09:39 UTC, closed without merging